language: python
python:
  - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get install daemontools redis-server
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
before_script:
  - flake8 feedhq
  - flake8 tests
script:
  - psql -c 'CREATE DATABASE feedhq;' -U postgres
  - PYTHONPATH=. make coverage
after_success:
  - coveralls
