language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install daemontools
install:
  - pip install -r requirements-dev.txt --use-mirrors
before_script:
  - flake8 feedhq
  - flake8 tests
script:
  - psql -c 'CREATE DATABASE feedhq;' -U postgres
  - PYTHONPATH=. make test
