language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -r requirements-dev.txt --use-mirrors
before_script:
  - flake8 feedhq
  - flake8 tests
script:
  - psql -c 'CREATE DATABASE feedhq;' -U postgres
  - PYTHONPATH=. make test
