language: python
python: "3.3"

services:
  - redis-server

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=lint
  - TOXENV=coverage

install:
  - pip install tox

script: "./.travis.sh"

matrix:
  allow_failures:
    - env: TOXENV=coverage
