language: python
python: "3.4"

services:
  - redis-server
  - elasticsearch

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=lint
  - TOXENV=coverage

install:
  - pip install tox

before_script:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.1.deb
  - sudo service elasticsearch stop
  - sudo dpkg -i elasticsearch-1.1.1.deb
  - sudo service elasticsearch start

script: "./.travis.sh"

matrix:
  allow_failures:
    - env: TOXENV=coverage
