language: python
python: "3.5"
cache: pip

services:
  - redis-server
  - elasticsearch

env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=lint
  - TOXENV=coverage
  - TOXENV=docs

install:
  - pip install tox

before_script:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb
  - sudo service elasticsearch stop
  - sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb
  - sudo service elasticsearch start
  - sleep 10

script: "./.travis.sh"

matrix:
  allow_failures:
    - env: TOXENV=coverage
